# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x05\x62ooks\"\x0e\n\x0c\x42ooksRequest\"+\n\rBooksResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book\"+\n\x0e\x41\x64\x64\x42ookRequest\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\",\n\x0f\x41\x64\x64\x42ookResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\"1\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2\x83\x01\n\x0c\x42ooksService\x12\x37\n\x08GetBooks\x12\x13.books.BooksRequest\x1a\x14.books.BooksResponse\"\x00\x12:\n\x07\x41\x64\x64\x42ook\x12\x15.books.AddBookRequest\x1a\x16.books.AddBookResponse\"\x00\x62\x06proto3')



_BOOKSREQUEST = DESCRIPTOR.message_types_by_name['BooksRequest']
_BOOKSRESPONSE = DESCRIPTOR.message_types_by_name['BooksResponse']
_ADDBOOKREQUEST = DESCRIPTOR.message_types_by_name['AddBookRequest']
_ADDBOOKRESPONSE = DESCRIPTOR.message_types_by_name['AddBookResponse']
_BOOK = DESCRIPTOR.message_types_by_name['Book']
BooksRequest = _reflection.GeneratedProtocolMessageType('BooksRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKSREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:books.BooksRequest)
  })
_sym_db.RegisterMessage(BooksRequest)

BooksResponse = _reflection.GeneratedProtocolMessageType('BooksResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKSRESPONSE,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:books.BooksResponse)
  })
_sym_db.RegisterMessage(BooksResponse)

AddBookRequest = _reflection.GeneratedProtocolMessageType('AddBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:books.AddBookRequest)
  })
_sym_db.RegisterMessage(AddBookRequest)

AddBookResponse = _reflection.GeneratedProtocolMessageType('AddBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKRESPONSE,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:books.AddBookResponse)
  })
_sym_db.RegisterMessage(AddBookResponse)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:books.Book)
  })
_sym_db.RegisterMessage(Book)

_BOOKSSERVICE = DESCRIPTOR.services_by_name['BooksService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKSREQUEST._serialized_start=22
  _BOOKSREQUEST._serialized_end=36
  _BOOKSRESPONSE._serialized_start=38
  _BOOKSRESPONSE._serialized_end=81
  _ADDBOOKREQUEST._serialized_start=83
  _ADDBOOKREQUEST._serialized_end=126
  _ADDBOOKRESPONSE._serialized_start=128
  _ADDBOOKRESPONSE._serialized_end=172
  _BOOK._serialized_start=174
  _BOOK._serialized_end=223
  _BOOKSSERVICE._serialized_start=226
  _BOOKSSERVICE._serialized_end=357
# @@protoc_insertion_point(module_scope)
