# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_pb2 as books__pb2


class BooksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBooks = channel.unary_unary(
                '/grpc.BooksService/GetBooks',
                request_serializer=books__pb2.BooksRequest.SerializeToString,
                response_deserializer=books__pb2.BooksResponse.FromString,
                )
        self.AddBook = channel.unary_unary(
                '/grpc.BooksService/AddBook',
                request_serializer=books__pb2.AddBookRequest.SerializeToString,
                response_deserializer=books__pb2.AddBookResponse.FromString,
                )


class BooksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooks,
                    request_deserializer=books__pb2.BooksRequest.FromString,
                    response_serializer=books__pb2.BooksResponse.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=books__pb2.AddBookRequest.FromString,
                    response_serializer=books__pb2.AddBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.BooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.BooksService/GetBooks',
            books__pb2.BooksRequest.SerializeToString,
            books__pb2.BooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.BooksService/AddBook',
            books__pb2.AddBookRequest.SerializeToString,
            books__pb2.AddBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
